rnaseq:
  root_dir: /proj/hoodlab/share/vcassen/rna-seq/rnaseq
  genomes_dir: /jdrf/data_var/solexa/genomes
  domain: ${root_dir}/templates

# "qsub" is the command used to submit a job to the cluster.  These items
# all relate to the submissing of cluster jobs.
qsub:
  host: aegir
  exe: /sge/bin/lx24-amd64/qsub
  template: qsub.template.generic
  ssh_cmd: ssh
