# some general values:
rnaseq:
  blat_indexes: /proj/hoodlab/share/programs/blat-indexes/not/here
  bowtie_indexes: /proj/hoodlab/share/programs/bowtie-indexes:/proj/hoodlab/share/programs/RNAseq-Pi/data/bowtie-indexes
  ensembl_dir: /proj/hoodlab/share/programs/Ensembl
  path: /tools/bin:/hpc/bin:/bin:/usr/bin/

  # Don't edit this section
  cmds:
    help: help.py
    run: run_pipeline.py
    ls: ls.py

# Don't edit this section
provenance:
  cmds:
    load_pipeline: load_pipeline.py
    pipeline_start: pipeline_start.py
    mid_step: mid_step.py
    pipeline_end: pipeline_end.py

# database
db: 
  db_name: db/provenance.sqlite3

# "qsub" is the command used to submit a job to and SGE cluster.  These items
# all relate to the submissing of cluster jobs.
qsub:
  host: aegir
  exe: /sge/bin/lx24-amd64/qsub
  template: qsub.template.generic
  ssh_cmd: /usr/bin/ssh
  nprocs: 4

# Don't edit this section
testing:
  template_dir: t/fixtures/templates
  test_db: t/fixtures/dbs/simple_orm.db