# some general values:
rnaseq:
  root_dir: /Users/victorcassen/random/isb/Rnaseq
  genomes_dir: /jdrf/data_var/solexa/genomes
  domain: ${root_dir}/templates

# database
db: 
  db_name: provenance.sqlite3
  tablename: provenance

# list of command understood by rnaseq and the file in which to find them
cmds:
  load: load.py
  sh: shell_script.py

# "qsub" is the command used to submit a job to the cluster.  These items
# all relate to the submissing of cluster jobs.
qsub:
  host: aegir
  exe: /sge/bin/lx24-amd64/qsub
  template: qsub.template.generic
  ssh_cmd: ssh

